DROP TABLE IF EXISTS members CASCADE;
DROP TABLE IF EXISTS books CASCADE;
DROP TABLE IF EXISTS copies CASCADE;
DROP TABLE IF EXISTS loans CASCADE;
DROP TABLE IF EXISTS fines CASCADE;

CREATE TABLE members (
    id SERIAL PRIMARY KEY,
    name VARCHAR (100) NOT NULL,
    email  VARCHAR(255) NOT NULL,
    member_type VARCHAR (100) NOT NULL DEFAULT 'Regular',
        CHECK (member_type IN ('regular', 'inactivo', 'activo')),
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE books (
    id SERIAL PRIMARY KEY,
    title VARCHAR (100) NOT NULL, 
    author VARCHAR(100) NOT NULL, 
    category VARCHAR(100) NOT NULL, 
    isbn VARCHAR(13) UNIQUE, 
);

CREATE TABLE copies (
    id SERIAL PRIMARY KEY,
    book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE RESTRICT,
    barcode VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'prestado' 
        CHECK (status IN ('prestado', 'perdido', 'existente')),
);

CREATE TABLE loans (
    id SERIAL PRIMARY KEY,
    copy_id  INTEGER NOT NULL REFERENCES copies(id) ON DELETE RESTRICT,
    member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
    loaned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    due_at TIMESTAMP DEFAULT,
    returned_at TIMESTAMP DEFAULT
);

CREATE TABLE fines (
    id SERIAL PRIMARY KEY,
    loan_id INTEGER NOT NULL REFERENCES loans(id) ON DELETE RESTRICT,
    amount,
    paid_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);